name: 'Deploy on release tag'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+\+?r?e?v?[0-9]?
      - v20[0-9][0-9].[0-1]?[1470].[0-9]+

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release-on-tag:
    uses: balena-os/github-workflows/.github/workflows/build_and_deploy.yml@136acb007187c74a9aef5b7c90371a3034026ea3
    with:
      deployTo: "staging"
      final: "no"
    secrets:
      jenkins_user: "alexg@balena.io"
      jenkins_token: "11942c49082f6e620e8c03df63f824e7eb"
